"""use Money and MoneyMapper for player balance

Revision ID: 0def35c0e162
Revises: 723dfa4628a3
Create Date: 2026-02-13 16:48:39.749853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0def35c0e162'
down_revision: Union[str, Sequence[str], None] = '723dfa4628a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
