"""drop all tables and create them again (players, clans and clan_members)

Revision ID: 5d5a54a927be
Revises:
Create Date: 2026-02-16 19:28:04.255120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d5a54a927be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('clans',
    sa.Column('clan_id', sa.UUID(), nullable=False),
    sa.Column('clan_name', sa.String(length=30), nullable=False),
    sa.Column('clan_tag', sa.String(length=6), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('clan_id'),
    sa.UniqueConstraint('clan_name'),
    sa.UniqueConstraint('clan_tag'),
    sa.UniqueConstraint('owner_id')
    )
    op.create_table('clan_members',
    sa.Column('clan_member_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('clan_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.clan_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('clan_member_id'),
    sa.UniqueConstraint('player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clan_members')
    op.drop_table('clans')
    op.drop_table('players')
    # ### end Alembic commands ###
