"""add items and inventory_items tables; remove default values from all tables

Revision ID: 65f49c418e7d
Revises: 5d5a54a927be
Create Date: 2026-02-22 16:28:09.307180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f49c418e7d'
down_revision: Union[str, Sequence[str], None] = '5d5a54a927be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=2083), nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('inventory_items',
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('item_amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('inventory_item_id'),
    sa.UniqueConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_items')
    op.drop_table('items')
    # ### end Alembic commands ###
